#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bal-khan <bal-khan@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/08/12 00:56:03 by bal-khan          #+#    #+#              #
#    Updated: 2014/08/12 00:56:06 by bal-khan         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

A=$(PARENTS)$(SRC)ft_atoi.c \
$(PARENTS)$(SRC)ft_bzero.c \
$(PARENTS)$(SRC)ft_isalnum.c \
$(PARENTS)$(SRC)ft_isalpha.c \
$(PARENTS)$(SRC)ft_isascii.c \
$(PARENTS)$(SRC)ft_isdigit.c \
$(PARENTS)$(SRC)ft_isprint.c \
$(PARENTS)$(SRC)ft_itoa.c \
$(PARENTS)$(SRC)ft_memalloc.c \
$(PARENTS)$(SRC)ft_memccpy.c \
$(PARENTS)$(SRC)ft_memchr.c \
$(PARENTS)$(SRC)ft_memcmp.c \
$(PARENTS)$(SRC)ft_memcpy.c \
$(PARENTS)$(SRC)ft_memdel.c \
$(PARENTS)$(SRC)ft_memmove.c \
$(PARENTS)$(SRC)ft_memset.c \
$(PARENTS)$(SRC)ft_putchar.c \
$(PARENTS)$(SRC)ft_putchar_fd.c \
$(PARENTS)$(SRC)ft_putendl.c \
$(PARENTS)$(SRC)ft_putendl_fd.c \
$(PARENTS)$(SRC)ft_putnbr.c \
$(PARENTS)$(SRC)ft_putnbr_fd.c \
$(PARENTS)$(SRC)ft_putstr.c \
$(PARENTS)$(SRC)ft_putstr_fd.c \
$(PARENTS)$(SRC)ft_strcat.c \
$(PARENTS)$(SRC)ft_strchr.c \
$(PARENTS)$(SRC)ft_strclr.c \
$(PARENTS)$(SRC)ft_strcmp.c \
$(PARENTS)$(SRC)ft_strcpy.c \
$(PARENTS)$(SRC)ft_strdel.c \
$(PARENTS)$(SRC)ft_strdup.c \
$(PARENTS)$(SRC)ft_strequ.c \
$(PARENTS)$(SRC)ft_striter.c \
$(PARENTS)$(SRC)ft_striteri.c \
$(PARENTS)$(SRC)ft_strjoin.c \
$(PARENTS)$(SRC)ft_strlcat.c \
$(PARENTS)$(SRC)ft_strlen.c \
$(PARENTS)$(SRC)ft_strmap.c \
$(PARENTS)$(SRC)ft_strmapi.c \
$(PARENTS)$(SRC)ft_strncat.c \
$(PARENTS)$(SRC)ft_strncmp.c \
$(PARENTS)$(SRC)ft_strncpy.c \
$(PARENTS)$(SRC)ft_strnequ.c \
$(PARENTS)$(SRC)ft_strnew.c \
$(PARENTS)$(SRC)ft_strnstr.c \
$(PARENTS)$(SRC)ft_strrchr.c \
$(PARENTS)$(SRC)ft_strsplit.c \
$(PARENTS)$(SRC)ft_strstr.c \
$(PARENTS)$(SRC)ft_strsub.c \
$(PARENTS)$(SRC)ft_strtrim.c \
$(PARENTS)$(SRC)ft_tolower.c \
$(PARENTS)$(SRC)ft_toupper.c

B=$(INCLUDES)ft_atoi.o \
$(INCLUDES)ft_bzero.o \
$(INCLUDES)ft_isalnum.o \
$(INCLUDES)ft_isalpha.o \
$(INCLUDES)ft_isascii.o \
$(INCLUDES)ft_isdigit.o \
$(INCLUDES)ft_isprint.o \
$(INCLUDES)ft_itoa.o \
$(INCLUDES)ft_memalloc.o \
$(INCLUDES)ft_memccpy.o \
$(INCLUDES)ft_memchr.o \
$(INCLUDES)ft_memcmp.o \
$(INCLUDES)ft_memcpy.o \
$(INCLUDES)ft_memdel.o \
$(INCLUDES)ft_memmove.o \
$(INCLUDES)ft_memset.o \
$(INCLUDES)ft_putchar.o \
$(INCLUDES)ft_putchar_fd.o \
$(INCLUDES)ft_putendl.o \
$(INCLUDES)ft_putendl_fd.o \
$(INCLUDES)ft_putnbr.o \
$(INCLUDES)ft_putnbr_fd.o \
$(INCLUDES)ft_putstr.o \
$(INCLUDES)ft_putstr_fd.o \
$(INCLUDES)ft_strcat.o \
$(INCLUDES)ft_strchr.o \
$(INCLUDES)ft_strclr.o \
$(INCLUDES)ft_strcmp.o \
$(INCLUDES)ft_strcpy.o \
$(INCLUDES)ft_strdel.o \
$(INCLUDES)ft_strdup.o \
$(INCLUDES)ft_strequ.o \
$(INCLUDES)ft_striter.o \
$(INCLUDES)ft_striteri.o \
$(INCLUDES)ft_strjoin.o \
$(INCLUDES)ft_strlcat.o \
$(INCLUDES)ft_strlen.o \
$(INCLUDES)ft_strmap.o \
$(INCLUDES)ft_strmapi.o \
$(INCLUDES)ft_strncat.o \
$(INCLUDES)ft_strncmp.o \
$(INCLUDES)ft_strncpy.o \
$(INCLUDES)ft_strnequ.o \
$(INCLUDES)ft_strnew.o \
$(INCLUDES)ft_strnstr.o \
$(INCLUDES)ft_strrchr.o \
$(INCLUDES)ft_strsplit.o \
$(INCLUDES)ft_strstr.o \
$(INCLUDES)ft_strsub.o \
$(INCLUDES)ft_strtrim.o \
$(INCLUDES)ft_tolower.o \
$(INCLUDES)ft_toupper.o

NAME =libft.a
DIRECTORY =./
INCLUDES =includes/
LIBFT =libft.a
SRC =src/
PARENTS =../
all: $(LIBFT)
	@echo "    /\**/\ "
	@echo "   ( o_o  )_) "
	@echo "   ,(u  u  ,),  Compilation complete"

$(LIBFT):
		@echo "               _    if Static Librairies are already made,"
		@echo "              | |      Remove them first !!"
		@echo "              | |===( )   ////////"
		@echo "              |_|   |||  ( ^   ^ )      (make fclean)"
		@echo "                     |||  \ =*= /                   ____"
		@echo "                      |||  \___/                    ||   \_"
		@echo "                       ||||||                       ||     |"
		@echo "                       ||||||                    ...||__/|-\""
		@echo "                       ||||||                 __|________|__"
		@echo "                         |||                 |______________|"
		@echo "                         |||                 || ||      || ||"
		@echo "                         |||                 || ||      || ||"
		@echo " ------------------------|||-----------------||-||------||-||-------"
		@echo "                         |__>                || ||      || ||"
		
		@cd $(INCLUDES) ; gcc -c -Wall -Wextra -Werror $(A) -I ./ #-fsanitize=address -g
		@ar rc $(NAME) $(B) 
		@ranlib $(NAME)
		@echo "                _________________________________________________"
		@echo "                |                                                | "
		@echo "                |                                                |_____    __ "
		@echo "                |  Static Librairies Succefully createds         |     |__|  |_________ "
		@echo "                |________________________________________________|     |::|  |        / "
		@echo "   /\**/\       |                                                \.____|::|__|       < "
		@echo "  ( o_o  )_     |                                                       \::/  \._______\ "
		@echo "   (u--u   \_)  | "
		@echo "    (||___   )==\ "
		@echo "  ,dP'/b/=( /P'/b\ "
		@echo "  |8 || 8\=== || 8 "
		@echo "  'b,  ,P  'b,  ,P "
		@echo "    ''''     '''' "

clean: 
	@rm -f $(B)
	@echo "    o"
	@echo " \_/\o"
	@echo "( Oo)                               \|/ "
	@echo "( = )  .===O-=-=-=-=-=-=-=-=-=-=-=-=-O- "
	@echo "/   \_/U:                           /|\ "
	@echo "||  |_/ "
	@echo "\\  |         Removing objects files"
	@echo "{K ||"
	@echo " | PP"
	@echo " | ||"
	@echo " (__\\"

fclean: clean
	@rm -f $(NAME)
	@echo "          Removing                /^^^/           /] "
	@echo "                                /   ]           / ] "
	@echo "    O   Librairies     _______/    ]___       /  ] "
	@echo "                      /                \_____/   / "
	@echo " O                  _/   [@]  \ \                \ "
	@echo "          ___//_    /..         | |                ] "
	@echo "   o     /o )   \/   VVVvvv\    | |         _/\    ] "
	@echo "     O<  )___\\_/\         |               /    \  ] "
	@echo "                    AAA^^^^^              /       \] "
	@echo "                     \_________\   \_____/ "
	@echo "                                \   \ "
	@echo "                                 \___\ "

re: fclean all

customclean: clean all fclean 	
